#! /bin/bash

# Copyright Sjors Sparreboom 2013-2018
# Distributed under the MIT License
# (See accompanying file LICENSE.md)

COMPILER="${1?}"
VERSION="${2?}" # has to be in fmt: x.x.x
MESON_VERSION=0.46.0

DOCKERFILE="docker/build/Dockerfile"

LLVM_URL="http://llvm.org/releases/${VERSION}/llvm-${VERSION}.src.tar.xz"
LIBCXX_URL="http://llvm.org/releases/${VERSION}/libcxx-${VERSION}.src.tar.xz"
LIBCXXABI_URL="http://llvm.org/releases/${VERSION}/libcxxabi-${VERSION}.src.tar.xz"
CLANG_URL="http://releases.llvm.org/${VERSION}/clang+llvm-${VERSION}-x86_64-linux-gnu-debian8.tar.xz"

# Make dependencies
CMAKE_URL="https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz"
MESON_URL="https://github.com/mesonbuild/meson/releases/download/${MESON_VERSION}/meson-${MESON_VERSION}.tar.gz"
NINJA_URL="https://nirbheek.in/files/binaries/ninja/linux-amd64/ninja"

# Library dependencies
JSONC_URL="https://github.com/json-c/json-c/archive/json-c-0.13.1-20180305.tar.gz"
LIBCURL_URL="https://curl.haxx.se/download/curl-7.60.0.tar.gz"
WIRING_PI_URL="git://git.drogon.net/wiringPi"

CC=""
CXX=""

if [[ ! -d ${DOCKERFILE%/*}  ]]; then
	mkdir -p ${DOCKERFILE%/*}
fi

echo 'FROM debian:stretch-slim' > $DOCKERFILE
echo 'ADD . /root'             >> $DOCKERFILE
echo 'CMD bash'                >> $DOCKERFILE

# (see: http://www.iasptk.com/ubuntu-fix-broken-package-best-solution)
echo 'RUN if [ -f /var/lib/apt/lists/lock ]; then rm /var/lib/apt/lists/lock; fi' >> $DOCKERFILE
echo 'RUN if [ -f /var/cache/apt/archives/lock ]; then rm /var/cache/apt/archives/lock; fi' >> $DOCKERFILE

echo 'RUN apt-get update --fix-missing && apt-get -y install wget gnupg' >> $DOCKERFILE

echo 'RUN \
	wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -' >> $DOCKERFILE

echo "RUN \
	echo '\n\
        deb http://deb.debian.org/debian stretch main\n\
        deb http://deb.debian.org/debian stretch-updates main\n\
        deb http://security.debian.org/debian-security stretch/updates main\n\
	# testing\n\
        deb http://ftp.us.debian.org/debian testing main\n\
        deb-src http://http.us.debian.org/debian testing main\n\
	# testing security\n\
	deb http://security.debian.org/ testing/updates main \n\
	deb-src http://security.debian.org/ testing/updates main\n\
	# unstable\n\
	deb http://http.us.debian.org/debian unstable main\n\
	deb-src http://http.us.debian.org/debian unstable main\n\
	# llvm toolchain\n\
	deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch main\n\
	deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch main\n\
	# clang 4.0\n\
	deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-4.0 main\n\
	deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-4.0 main\n\
	# # clang 5.0\n\
	deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main\n\
	deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-5.0 main\n\
	# # clang 6.0\n\
	deb http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main\n\
	deb-src http://apt.llvm.org/stretch/ llvm-toolchain-stretch-6.0 main\n\
	' > /etc/apt/sources.list
	" >> $DOCKERFILE

echo "RUN \
	echo \"\n\
	Package: *\n\
	Pin: release a=stable\n\
	Pin-Priority: 1000\n\
	Package: *\n\
	Pin: release a=testing\n\
	Pin-Priority: 500\n\
	Package: *\n\
	Pin: release a=unstable\n\
	Pin-Priority: 250\n\
	\n\
	Package: *\n\
	Pin: release a=llvm-toolchain-stretch-${VERSION%.*}\n\
	Pin-Priority: 2\" > /etc/apt/preferences" >> $DOCKERFILE

# (see: http://www.iasptk.com/ubuntu-fix-broken-package-best-solution)
echo 'RUN if [ -f /var/lib/apt/lists/lock ]; then rm /var/lib/apt/lists/lock; fi' >> $DOCKERFILE
echo 'RUN if [ -f /var/cache/apt/archives/lock ]; then rm /var/cache/apt/archives/lock; fi' >> $DOCKERFILE

echo 'RUN apt-get update --fix-missing && apt-get -y install \
  bash                                   \
  dialog                                 \
  apt-utils                              \
  libcurl4                               \
  libgtk-3-dev                           \
  pkg-config                             \
  sudo                                   \
  binutils                               \
  xz-utils                               \
  python3-dev                            \
  make                                   \
  doxygen                                \
  git                                    \
  tar'                  >> $DOCKERFILE

# Get the latest cmake
echo "RUN \
        wget -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C /usr/local" >> $DOCKERFILE

# Get the latest ninja
echo "RUN \
	mkdir -p /root/tools; \
        wget ${NINJA_URL} -O /root/tools/ninja; \
	chmod +x /root/tools/ninja; \
	ln -s /root/tools/ninja /usr/local/bin/ninja;" >> $DOCKERFILE

# Get the latest meson
echo "RUN \
	wget --no-check-certificate --quiet -O - ${MESON_URL} | tar --strip-components=1 -xz -C /root/tools; \
	ln -s /root/tools/meson.py /usr/local/bin/meson;" >> $DOCKERFILE

# Get the latest json-c
echo "RUN \
     mkdir -p /root/deps/json/build; \
       wget --no-check-certificate --quiet -O - ${JSONC_URL} | tar --strip-components=1 -xz -C /root/deps/json" >> $DOCKERFILE

# Get the latest libcurl
echo "RUN \
     mkdir -p /root/deps/libcurl; \
       wget --no-check-certificate --quiet -O - ${LIBCURL_URL} | tar --strip-components=1 -xz -C /root/deps/libcurl" >> $DOCKERFILE

# Get the latest wiringPi
echo "RUN \
     mkdir -p /root/deps/wiringPi; \
       git clone ${WIRING_PI_URL} /root/deps/wiringPi" >> $DOCKERFILE

if [[ "$COMPILER" = "clang" || "${COMPILER}" = "clang++" ]]; then
	  echo "RUN apt-get -y install \
		clang-${VERSION%.*}" >> $DOCKERFILE
fi

if [[ "$COMPILER" = "gcc" || "${COMPILER}" = "g++" ]]; then
	  echo "RUN apt-get -y install \
		gcc-${VERSION%%.*}    \
		g++-${VERSION%%.*}" >> $DOCKERFILE
fi
